version: '3'

services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./Backend
    restart: always
    ports:
      - "9600:9600"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

  frontend:
    build: ./Front
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend


volumes:
  db_data:
