version: '3'

services:
  frontend:
    build: ./Front
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./Backend
    restart: always
    ports:
      - "9600:9600"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
