version: '3'
services:
  web:
    image: python:3.9
    container_name: django_app
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && gunicorn your_project_name.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    depends_on:
      - web

volumes:
  postgres_data:
