# Generated by Django 5.1.1 on 2024-09-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='command2',
            new_name='command',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='command1',
        ),
    ]
