# Generated by Django 5.1.1 on 2024-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_linck_ava_command_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='image_data',
        ),
        migrations.AddField(
            model_name='command',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='images/'),
        ),
    ]
