# Generated by Django 5.1.1 on 2024-09-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_command_image_data_command_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
