# Generated by Django 5.1.1 on 2024-09-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_command2_matches_command_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='linck_ava',
            new_name='image_data',
        ),
    ]
